###############################################################
# Testbed Compute Containers
# 
# These are the compute containers needed for basic unit testing.
###############################################################

ssh:
  image: agaveplatform/sshd:latest
  command: "-p 10011"
  restart: on-failure
  ports:
    - '10011:10011'

sshtunnel:
  image: agaveplatform/sshd:latest
  command: "-p 10199"
  restart: on-failure
  ports:
    - '10199:10199'

sshhidden:
 image: agaveplatform/sshd:latest
 restart: on-failure
 ports:
   - '10198:22'

      
gsissh:
  image: agaveapi/gridftp:5
  hostname: docker.example.com
  ports:
    - '2222:2222'
    - '2022:22'
    - '7515:7512'

slurm:
  image: agaveplatform/slurm:14.03.9
  hostname: docker.example.com
  ports:
    - '10133:22'

torque:
  image: agaveplatform/torque:5.0.0
  hostname: docker.example.com
  privileged: true
  ports:
    - '10144:22'

htcondor:
  image: agaveplatform/htcondor:8.4.9
  hostname: docker.example.com
  ports:
    - '10155:22'

gridengine:
  image: agaveplatform/gridengine:6.2
  hostname: docker.example.com
  environment:
    - "HOSTNAME=docker.example.com"
  privileged: true
  ports:
    - '10166:22'
    - '6444:6444'
    - '6445:6445'
    
openlava:
  image: agaveplatform/openlava:3.3
  hostname: docker.example.com
  ports:
    - '10177:22' 
    - '6879:6879'
    - '6878:6878'
    - '6882:6882'
    - '6881:6881'

