##############################################################
#  Development Stack of Dependent Services
#############################################################

version: '3.3'

volumes:
  mysql_data:
  mongo_data:

networks:
  services:

services:
  ##############################################################
  # Java & Maven enabled platform
  ##############################################################
  utest:
    #image values: agaveapi/slave-mvn-runner:1.0 for jenkins vs. agaveapi/mvn-runner for mac virtualbox setup
    image: ${IMAGE}
    command: sh /sources/config/testbed/run-utests.sh
    #command: sleep 1200
    labels:
      agaveapi.test: "utest"
    environment:
      MODULE: ${MODULE}
      SUITE: ${SUITE}
      USER_HOME: ${USER_HOME}
    networks:
      - services
    volumes:
      - ../..:/sources
      - ~/.m2:${USER_HOME}/.m2
      #- ~/.docker:/root/.docker:ro
      #- /var/run/docker.sock:/docker.sock

  ##############################################################
  # MySQL
  ##############################################################
  mysql:
    image: agaveapi/mysql:5.6-devtz
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeit
      MYSQL_DATABASE: agavecore
      MYSQL_USER: agaveuser
      MYSQL_PASSWORD: password
      MYSQL_TEST_DATABASE: test
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      labels:
        agaveapi.test: "utest"
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M


##############################################################
# MongoDB
##############################################################
  mongodb:
    image: agaveplatform/mongodb:2.6
    hostname: mongodb
    environment:
      - MONGODB_ADMIN_PASS=changeit
      - MONGODB_PASSWORD=password
      - MONGODB_USERNAME=agaveuser
      - MONGODB_DATABASE=api
    volumes:
      - mongo_data:/data
    ports:
      - '27017:27017'
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M


##############################################################
# Beanstalkd
##############################################################
  beanstalkd:
    image: agaveplatform/beanstalkd:latest
    command: /usr/bin/beanstalkd -b /var/lib/beanstalkd/binlog
    hostname: beanstalkd
    ports:
      - '11300:11300'
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  ##############################################################
  # Mail
  ##############################################################
  #mail:
  #  image: tvial/docker-mailserver
  #  hostname: mail
  #  domainname: domain.com
  #  # your FQDN will be 'mail.domain.com'
  #  ports:
  #  - "25:25"
  #  - "143:143"
  #  - "587:587"
  #  - "993:993"
  #  volumes:
  #  - ./spamassassin:/tmp/spamassassin/
  #  - ./postfix:/tmp/postfix/

  myproxy:
    image: agaveapi/myproxy
    #hostname: docker.example.com
    labels:
      agaveapi.test: "utest"
    networks:
      - services
    ports:
      - '22'
      - '7512'
      - '7513'
    environment:
      - 'GLOBUS_GSSAPI_FORCE_TLS=1'

  sftp:
    image: agaveplatform/centos-base
    labels:
      agaveapi.test: "utest"
    networks:
      - services
    ports:
      - '22'

  sftptunnel:
    image: agaveplatform/centos-base
    #hostname: tunnel.example.com
    labels:
      agaveapi.test: "utest"
    networks:
      - services
    privileged: true
    #links:
    #  - sftphidden
    ports:
      - '22'

  sftphidden:
    image: agaveplatform/centos-base
    #hostname: docker.example.com
    labels:
      agaveapi.test: "utest"
    networks:
      - services
    ports:
      - '22'

  irods:
    image: agaveplatform/irods:3.3.1
    #hostname: docker.example.com
    labels:
      agaveapi.test: "utest"
    networks:
      - services
    ports:
      - '22'
      - '1247'

  irodspam:
    image: agaveplatform/irods-pam:latest
    #hostname: docker.example.com
    labels:
      agaveapi.test: "utest"
    networks:
      - services
    ports:
      - '22'
      - '1247'

  irods4:
    image: agaveplatform/irods:4.0.3
    command: changeit
    #hostname: docker.example.com
    labels:
      agaveapi.test: "utest"
    networks:
      - services
    environment:
      - 'DOCKER_HOSTNAME=docker.example.com'
      - 'IRODS_ZONE=iplant'
    ports:
      - '1247'

  http:
    image: agaveplatform/apache-dev
    #hostname: docker.example.com
    labels:
      agaveapi.test: "utest"
    networks:
      - services
    ports:
      - '22'
      - '80'
      - '443'

  ftp:
    image: agaveplatform/pure-ftpd
    #hostname: docker.example.com
    labels:
      agaveapi.test: "utest"
    networks:
      - services
    privileged: true
    ports:
      - '20'
      - '21'
      - '22'
      - '30000-30009'

  gridftp:
    image: agaveplatform/gridftp:5
    #hostname: docker.example.com
    labels:
      agaveapi.test: "utest"
    networks:
      - services
    extra_hosts:
      - 'tests.example.com:192.168.99.1'
      - 'dooley-mac.local:192.168.99.1'
    privileged: true
    ports:
      - '22'
      - '2811'
      - '7512'
      - '50000-50100'
    environment:
      - 'GLOBUS_TCP_PORT_RANGE=50000,50100'

##############################################################
# Pushpin
##############################################################
  pushpin:
    image: agaveplatform/pushpin:1.6.0
    extra_hosts:
      - 'realtime.api.agave:192.168.99.100'
    hostname: realtime.docker.example.com
    ports:
      - '7999:7999'
      - '5561:5561'
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
