##############################################################
#  Development Stack of Dependent Services
#############################################################

##############################################################
# MySQL
##############################################################
version: '3.4'

volumes:
  mysql_data:
  mongo_data:

networks:
  services:
  realtime:

services:
  mysql:
    image: bitnami/mariadb
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: changeit
      MARIADB_DATABASE: agavecore
      MARIADB_USER: agaveuser
      MARIADB_PASSWORD: password
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

#  migrate:
#    image: agaveplatform/agave-migrations:2.2.6
#    depends_on:
#     - mysql
#    environment:
#      - 'MYSQL_HOST=mysql'
#      - 'MYSQL_USER=agaveuser'
#      - 'MYSQL_PASSWORD=password'
#      - 'MYSQL_DATABASE=agavecore'
#    command: "./flyway migrate"

  ##############################################################
  # MongoDB 2.6
  ##############################################################
  mongodb:
    image: agaveplatform/mongodb:2.6
    hostname: mongodb
    environment:
      - MONGODB_ADMIN_PASS=changeit
      - MONGODB_PASSWORD=password
      - MONGODB_USERNAME=agaveuser
      - MONGODB_DATABASE=api
    volumes:
      - mongo_data:/data
    ports:
      - '27017:27017'
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M


#  ##############################################################
#  # MongoDB - 3.4
#  ##############################################################
#  mongodb34:
#    image: agaveapi/mongodb:3.4
#    hostname: mongodb
#    mem_limit: 512m
#    restart: on-failure
#    environment:
#      - MONGODB_ADMIN_PASS=changeit
#      - MONGODB_PASSWORD=password
#      - MONGODB_USERNAME=agaveuser
#      - MONGODB_DATABASE=api
#    volumes_from:
#      - mongodbvol
#    ports:
#      - '27018:27017'
#    labels:
#      - "traefik.enable=false"
#    networks:
#      - services
#
#  mongodb34vol:
#    image: agaveapi/mongodb:3.4
#    command: sleep 120
#    mem_limit: 64m
#    labels:
#      - "traefik.enable=false"
#    networks:
#      - services

  ##############################################################
  # Beanstalkd
  ##############################################################
  beanstalkd:
    image: agaveplatform/beanstalkd:latest
    command: /usr/bin/beanstalkd -b /var/lib/beanstalkd/binlog
    hostname: beanstalkd
    ports:
      - '11300:11300'
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  beanstalkd-console:
      image: kusmierz/beanstalk-console:latest
      ports:
        - '9999:80'
      labels:
        - "traefik.enable=false"
      networks:
        - services
      deploy:
        restart_policy:
          condition: on-failure
        resources:
          limits:
            memory: 512M
          reservations:
            memory: 128M

  ##############################################################
  # Pushpin
  ##############################################################
#  pushpin:
#    image: agaveplatform/pushpin:1.6.0
#    hostname: realtime.example.com
#    ports:
#      - '7999:7999'
#      - '5561:5561'
#    labels:
#      - "traefik.enable=false"
#    networks:
#      - realtime
#    deploy:
#      restart_policy:
#        condition: on-failure
#      resources:
#        limits:
#          memory: 512M
#        reservations:
#          memory: 256M

  ##############################################################
  # Fluentd
  ##############################################################

#  fluentd:
#    image: fluent/fluentd
#    hostname: fluentd.example.com
#    restart: on-failure
#    ports:
#      - 24224:24224
#    volumes:
#      - ../logs/fluentd:/fluentd/log
#    labels:
#      - "traefik.enable=false"
#    networks:
#      - default

networks:
  services:
  realtime:

