##############################################################
#  Development Stack of Dependent Services
#############################################################

##############################################################
# MySQL
##############################################################
version: '3.7'

volumes:
  mysql_data:
  mongo_data:

networks:
  services:

services:
  mysql:
    image: agave-mariadb:2.2.27
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: changeit
      MARIADB_DATABASE: agavecore
      MARIADB_USER: agaveuser
      MARIADB_PASSWORD: password
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    image: redis:latest
    restart: on-failure
    ports:
      - 6379:6379

#  migrate:
#    image: agaveplatform/agave-migrations:2.2.6
#    depends_on:
#     - mysql
#    environment:
#      - 'MYSQL_HOST=mysql'
#      - 'MYSQL_USER=agaveuser'
#      - 'MYSQL_PASSWORD=password'
#      - 'MYSQL_DATABASE=agavecore'
#    command: "./flyway migrate"

#  ##############################################################
#  # MongoDB 3.0
#  ##############################################################
#  mongodb:
#    image: agaveplatform/mongodb:3.0
#    hostname: mongodb
#    environment:
#      - MONGODB_ADMIN_PASS=changeit
#      - MONGODB_PASSWORD=password
#      - MONGODB_USERNAME=agaveuser
#      - MONGODB_DATABASE=api
#      - JOURNALING=no
#    volumes:
#      - mongo_data:/data
#    ports:
#      - '27017:27017'
#    labels:
#      - "traefik.enable=false"
#    networks:
#      - services
#    deploy:
#      restart_policy:
#        condition: on-failure
#      resources:
#        limits:
#          memory: 512M
#        reservations:
#          memory: 256M


  ##############################################################
  # MongoDB 3.0
  ##############################################################
  mongodb:
    image: agaveplatform/mongodb:3.0
    hostname: mongodb
    environment:
      - MONGODB_ADMIN_PASS=changeit
      - MONGODB_PASSWORD=password
      - MONGODB_USERNAME=agaveuser
      - MONGODB_DATABASE=api
      - JOURNALING=no
    volumes:
      - mongo_data:/data
    ports:
      - '27017:27017'
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  ##############################################################
  # Beanstalkd
  ##############################################################
  beanstalkd:
    image: agaveplatform/beanstalkd:latest
    command: /usr/bin/beanstalkd -b /var/lib/beanstalkd/binlog
    hostname: beanstalkd
    ports:
      - '11300:11300'
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M


  beanstalkd-console:
      image: kusmierz/beanstalk-console:latest
      ports:
        - '9999:80'
      labels:
        - "traefik.enable=false"
      networks:
        - services
      deploy:
        restart_policy:
          condition: on-failure
        resources:
          limits:
            memory: 512M
          reservations:
            memory: 128M



  ##############################################################
  # Pushpin
  ##############################################################
#  pushpin:
#    image: agaveplatform/pushpin:1.6.0
#    hostname: realtime.example.com
#    ports:
#      - '7999:7999'
#      - '5561:5561'
#    labels:
#      - "traefik.enable=false"
#    networks:
#      - realtime
#    deploy:
#      restart_policy:
#        condition: on-failure
#      resources:
#        limits:
#          memory: 512M
#        reservations:
#          memory: 256M

networks:
  services:
  realtime:

