##############################################################
#  Core Services Persistence Stack
#############################################################
version: '2'

services:
  ##############################################################
  # MySQL 5.7 / MariaDB 10.3
  ##############################################################
  mysql:
    image: agave-mariadb:2.2.27
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: changeit
      MARIADB_DATABASE: agavecore
      MARIADB_USER: agaveuser
      MARIADB_PASSWORD: password
    labels:
      - "traefik.enable=false"
    restart: on-failure
    mem_limit: 512M
    mem_reservation: 256M


  ##############################################################
  # MongoDB 4.2.8
  ##############################################################
  mongodb:
    image: agaveplatform/mongodb:4.2.8
    environment:
      - MONGODB_ADMIN_PASS=changeit
      - MONGODB_PASSWORD=password
      - MONGODB_USERNAME=agaveuser
      - MONGODB_DATABASE=api
      - JOURNALING=no
    ports:
      - '27017:27017'
    labels:
      - "traefik.enable=false"
    restart: on-failure
    mem_limit: 512M
    mem_reservation: 256M

  ##############################################################
  # Beanstalkd
  ##############################################################
  beanstalkd:
    image: agaveplatform/beanstalkd:latest
    command: /usr/bin/beanstalkd -b /var/lib/beanstalkd/binlog
    ports:
      - '11300:11300'
    labels:
      - "traefik.enable=false"
    restart: on-failure
    mem_limit: 512M
    mem_reservation: 128M

#  beanstalkd-console:
#      image: kusmierz/beanstalk-console:latest
#      ports:
#        - '9999:80'
#      labels:
#        - "traefik.enable=false"
#      networks:
#        - core_persistence
#      deploy:
#        restart_policy:
#          condition: on-failure
#        resources:
#          limits:
#            memory: 512M
#          reservations:
#            memory: 128M

  ##############################################################
  # Pushpin
  ##############################################################
#  pushpin:
#    image: agaveplatform/pushpin:1.6.0
#    hostname: realtime.example.com
#    ports:
#      - '7999:7999'
#      - '5561:5561'
#    labels:
#      - "traefik.enable=false"
#    networks:
#      - realtime
#    deploy:
#      restart_policy:
#        condition: on-failure
#      resources:
#        limits:
#          memory: 512M
#        reservations:
#          memory: 256M

