Agave\Bundle\ApiBundle\Entity\Authconfigs:
    type: entity
    table: authconfigs
    indexes:
        FKAB65DAC9D0F7341D:
            columns:
                - authentication_system_id
        FKAB65DAC98B60DEA6:
            columns:
                - remote_config_id
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        created:
            type: datetime
            nullable: false
        credential:
            type: string
            nullable: true
            length: 32768
            fixed: false
        internalUsername:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: internal_username
        lastUpdated:
            type: datetime
            nullable: false
            column: last_updated
        password:
            type: string
            nullable: true
            length: 128
            fixed: false
        systemDefault:
            type: boolean
            nullable: true
            column: system_default
        loginCredentialType:
            type: string
            nullable: false
            length: 16
            fixed: false
            column: login_credential_type
        username:
            type: string
            nullable: true
            length: 32
            fixed: false
        privateKey:
            type: string
            nullable: true
            length: 4098
            fixed: false
            column: private_key
        publicKey:
            type: string
            nullable: true
            length: 4098
            fixed: false
            column: public_key
    manyToOne:
        remoteConfig:
            targetEntity: Remoteconfigs
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                remote_config_id:
                    referencedColumnName: id
            orphanRemoval: false
        authenticationSystem:
            targetEntity: Credentialservers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                authentication_system_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
