Agave\Bundle\ApiBundle\Entity\MetadataPermissions:
    type: entity
    table: metadata_permissions
    uniqueConstraints:
        id:
            columns:
                - id
        uuid:
            columns:
                - uuid
                - username
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lastUpdated:
            type: datetime
            nullable: false
            column: last_updated
        permission:
            type: string
            nullable: false
            length: 16
            fixed: false
        username:
            type: string
            nullable: false
            length: 32
            fixed: false
        uuid:
            type: string
            nullable: false
            length: 255
            fixed: false
        tenantId:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: tenant_id
    lifecycleCallbacks: {  }
