Agave\Bundle\ApiBundle\Entity\SoftwarePermissions:
    type: entity
    table: software_permissions
    indexes:
        FKCD9271EC41F2F66B:
            columns:
                - software_id
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lastUpdated:
            type: datetime
            nullable: false
            column: last_updated
        permission:
            type: string
            nullable: false
            length: 16
            fixed: false
        username:
            type: string
            nullable: false
            length: 32
            fixed: false
    manyToOne:
        software:
            targetEntity: Softwares
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                software_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
