Agave\Bundle\ApiBundle\Entity\SoftwareInputs:
    type: entity
    table: software_inputs
    indexes:
        FKF4C1638159B3FD5F:
            columns:
                - software
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        created:
            type: datetime
            nullable: false
        defaultValue:
            type: string
            nullable: true
            length: 255
            fixed: false
            default: ''
            column: default_value
        description:
            type: string
            nullable: true
            length: 32768
            fixed: false
        fileTypes:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: file_types
        outputKey:
            type: string
            nullable: false
            length: 64
            fixed: false
            column: output_key
        label:
            type: string
            nullable: true
            length: 64
            fixed: false
        lastUpdated:
            type: datetime
            nullable: false
            column: last_updated
        minCardinality:
            type: integer
            nullable: true
            unsigned: false
            column: min_cardinality
        ontology:
            type: string
            nullable: true
            length: 255
            fixed: false
        displayOrder:
            type: integer
            nullable: false
            unsigned: false
            column: display_order
        required:
            type: boolean
            nullable: true
        validator:
            type: string
            nullable: true
            length: 255
            fixed: false
        visible:
            type: boolean
            nullable: true
        cliArgument:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: cli_argument
        showCliArgument:
            type: boolean
            nullable: false
            column: show_cli_argument
        enquote:
            type: boolean
            nullable: false
        maxCardinality:
            type: integer
            nullable: false
            unsigned: false
            default: '-1'
            column: max_cardinality
        repeatCliArgument:
            type: boolean
            nullable: false
            column: repeat_cli_argument
    manyToOne:
        software:
            targetEntity: Softwares
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                software:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        softwares:
            targetEntity: Softwares
            cascade: {  }
            mappedBy: inputs
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
