Agave\Bundle\ApiBundle\Entity\Systemroles:
    type: entity
    table: systemroles
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        created:
            type: datetime
            nullable: false
        lastUpdated:
            type: datetime
            nullable: false
            column: last_updated
        role:
            type: string
            nullable: false
            length: 32
            fixed: false
        username:
            type: string
            nullable: false
            length: 32
            fixed: false
    lifecycleCallbacks: {  }
