###############################################################
# Core Science APIs - Dev
# lb-proxy.yml
#
# This is the base orchestration file to start Agave's Core Science
# API proxy load balancer. The APIs are accessible behind  this
# proxy which shields them from the outside world. Containers are assigned
# static ports to enable rolling updates of each API as needed.
# Containers performing data operations are assigned a partition
# of the default GridFTP and FTP port ranges to enable proper
# operation of the protocol from within each container.
#
# Make sure a.proxy.host and b.proxy.host point to the ip addresses
# of the hosts on which the core services are running.
#
###############################################################
---
version: '3.3'

services:
  localproxy:
    build:
      context: apache
    image: apache-api-proxy:devel
    net: host
    environment:
      - 'BALANCER_WHITELIST=all'
      - 'STATUS_WHITELIST=all'
      - 'LOG_TARGET_STDOUT=1'
      - 'LOG_LEVEL_DEBUG=1'
    volumes:
      - './logs/proxy:/var/log/apache2'
