##############################################################
#  OPTIONAL: Persistent beanstalkd instance
#############################################################
version: '3.3'

volumes:
  mongo_data:

services:
  beanstalkd:
    image: agaveplatform/beanstalkd:latest
    command: /usr/bin/beanstalkd -b /var/lib/beanstalkd/binlog
    ports:
      - '11300:11300'
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

  beanstalkd-console:
    image: kusmierz/beanstalk-console:latest
    ports:
      - '9999:80'
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M