##############################################################
#  OPTIONAL: MySQL Master-Slave cluster with replication
#############################################################
version: '3.3'

volumes:
  mongo_data:

networks:
  services:

services:
  mysql:
    image: agaveplatform/agave-mariadb:2.2.27
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: changeit
      MARIADB_DATABASE: agavecore
      MARIADB_USER: agaveuser
      MARIADB_PASSWORD: password
      REPLICATION_MASTER: true
      REPLICATION_PASS: rep_pass_change_me
      ON_CREATE_DB: db
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  mysql-slave:
    image: agave-mariadb:2.2.27
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: changeit
      MARIADB_DATABASE: agavecore
      MARIADB_USER: agaveuser
      MARIADB_PASSWORD: password
      REPLICATION_SLAVE: true
      REPLICATION_PASS: rep_pass_change_me
      ON_CREATE_DB: db
    labels:
      - "traefik.enable=false"
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M


###############################################################
#   OPTIONAL: Automated MySQL backup to S3
##############################################################

mysql-cron:
  image: sillelien/tutum-cron
  restart: always
  cpu_shares: 128
  mem_limit: 64m
  roles:
    - global
  environment:
    MYSQLBACKUP_HOURLY_CRON_SCHEDULE: '0 * * * *'
    MYSQLBACKUP_DAILY_CRON_SCHEDULE: '0 3 * * *'
  links:
    - mysqlbackup_hourly
    - mysqlbackup_daily
  tags:
    - staging
    - db
    - slave

mysqlbackup_hourly:
  image: sillelien/docker-mysql-backup
  command: backup
  links:
    - mysql:mysql
  environment:
    AWS_ACCESS_KEY_ID: key_id_change_me
    AWS_SECRET_ACCESS_KEY: "secret_change_me"
    AWS_DEFAULT_REGION: eu-west-1
    S3_BUCKET: s3_bucket_change_me
    S3_PATH: hourly
  tags:
    - staging
    - db
    - slave

mysqlbackup_daily:
  image: sillelien/docker-mysql-backup
  command: backup
  links:
    - mysql:mysql
  environment:
    AWS_ACCESS_KEY_ID: key_id_change_me
    AWS_SECRET_ACCESS_KEY: "secret_change_me"
    AWS_DEFAULT_REGION: eu-west-1
    S3_BUCKET: s3_bucket_change_me
    S3_PATH: daily
  tags:
    - staging
    - db
    - slave
